export const ActionTypes = {
  CLEAN_STATE:"CLEAN_STATE",

  UPDATE_STATUS: "UPDATE_STATUS",
  CREATE_APPOINTMENT_START: "CREATE_APPOINTMENT_START",
  CREATE_APPOINTMENT_SUCCESS: "CREATE_APPOINTMENT_SUCCESS",
  CREATE_APPOINTMENT_FAILURE:"CREATE_APPOINTMENT_FAILURE",

  UPDATE_AP_START:"UPDATE_AP_START",
  UPDATE_AP_SUCCESS:"UPDATE_AP_SUCCESS",
  UPDATE_AP_FAILURE:"UPDATE_AP_FAILURE",

  GET_APPOINTMENT: "GET_APPOINTMENT",
  GET_APPOINTMENT_FAILURE:"GET_APPOINTMENT_FAILURE",

  GET_TODAY_APPOINTMENT_SUCCESS:"GET_TODAY_APPOINTMENT_SUCCESS",
  GET_TODAY_APPOINTMENT_FAILURE:"GET_TODAY_APPOINTMENT_FAILURE",
  
  CANCEL_APPOINTMENT_START: "CANCEL_APPOINTMENT_START",
  CANCEL_APPOINTMENT_SUCCESS:"CANCEL_APPOINTMENT_SUCCESS",
  CANCEL_APPOINTMENT_FAILURE:"CANCEL_APPOINTMENT_FAILURE",

  UPDATE_PROFILE: "UPDATE_PROFILE",
  LOGIN_USER_START: "LOGIN_USER_START",
  LOGIN_USER_SUCCESS: "LOGIN_USER_SUCCESS",
  LOGIN_USER_FAILURE: "LOGIN_USER_FAILURE",

  SIGNUP_USER_START: "SIGNUP_USER_START",
  SIGNUP_USER_SUCCESS: "SIGNUP_USER_SUCCESS",
  SIGNUP_USER_FAILURE: "SIGNUP_USER_FAILURE",

  SIGNUP_DOCTOR: "SIGNUP_DOCTOR",
  CREATE_USER_START: "CREATE_USER_START",
  CREATE_USER_SUCCESS: "CREATE_USER_SUCCESS",
  CREATE_USER_FAILURE: "CREATE_USER_FAILURE",

  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  LOGOUT_FAILURE: "LOGOUT_FAILURE",

  GET_USER_START: "GET_USER_START",
  GET_USER_SUCCESS: "GET_USER_SUCCESS",
  GET_USER_FAILURE: "GET_USER_FAILURE",
  GET_ALL_DOC: "GET_ALL_DOC",

  UPDATE_USER_START: "UPDATE_USER_START",
  UPDATE_USER_SUCCESS: "UPDATE_USER_SUCCESS",
  UPDATE_USER_FAILURE: "UPDATE_USER_FAILURE",

  GET_ALL_PATIENTS: "GET_ALL_PATIENTS",
};
